#######################
# Aurea Central Jervis Example
#######################
# User guide and documentation can be found at: https://github.com/trilogy-group/aurea-central-jervis-example
# This project is based on https://github.com/aurea-central-jervis-example/aurea-central-jervis

language: java

before_install:
  - echo "In before install"
  - echo $PATH
  - bash
  - echo $PATH
#  - export PATH=$PATH:/home/jenkins/.sdkman/candidates/gradle/current/bin

install:
  - echo "Here we can override build"
  - bash gradle assemble


env:
 - Test1="test"

before_script:
  - echo "this is before script section"
  - whoami
  - pwd

#script:
#  - echo "Here we can override test"

stability: None

branches:
  only:
    - master
    - release
    - develop
    - feature

cache:
  directories:
    - ${HOME}/.m2
    - ${HOME}/.gradle
    - ${HOME}/.sdkman


jenkins:
  platform: docker
  os: ubuntu1604


